from .grand_line_auction_constants import (
    GRAND_LINE_AUCTION_CATEGORIES,
    GRAND_LINE_AUCTION_TEXT_CHANNELS,
)

MIN_INITIAL_BID = 100_000
MIN_AUCTION_VALUE = 400_000

# 10 mins minimum time for a speed auction
MIN_SPEED_AUCTION_SECONDS = 600
MAX_SPEED_AUCTION_SECONDS = 3600

MIN_REGULAR_AUCTION_SECONDS = 3600  # 1hr
MAX_REGULAR_AUCTION_SECONDS = 18000  # 5hrs

AUCTION_CATEGORY_LIST = [
    GRAND_LINE_AUCTION_CATEGORIES.BULK_AUCTION,
    GRAND_LINE_AUCTION_CATEGORIES.SHINY_AUCTION,
    GRAND_LINE_AUCTION_CATEGORIES.LEGENDARY_AUCTION,
    GRAND_LINE_AUCTION_CATEGORIES.MEGA_AUCTION,
    GRAND_LINE_AUCTION_CATEGORIES.OTHER_AUCTIONS,
    GRAND_LINE_AUCTION_CATEGORIES.GOLDEN_AUCTION,
    GRAND_LINE_AUCTION_CATEGORIES.EXCLUSIVE_AUCTIONS,
    GRAND_LINE_AUCTION_CATEGORIES.GIGANTAMAX_AUCTION,
]
